name: Lint Project
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/lint.yml
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - 'rust-toolchain.toml'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/lint.yml
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - 'rust-toolchain.toml'

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4 # stable

      - name: Rust cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: Lint project
        run: cargo clippy
